global_costmap:
  global_frame: map
  robot_base_frame: base_link

  update_frequency: 10.0
  publish_frequency: 10.0
  transform_tolerance: 0.5
  resolution: 0.1
  static_map: true

  inflation_layer:
    enabled:              true
    cost_scaling_factor:  0.05  # exponential rate at which the obstacle cost drops off (default: 10)
    inflation_radius:     0.1   # max. distance from an obstacle at which costs are incurred for planning paths. Inc. results in lower costs

  plugins:
    - {name: static_layer,                   type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer,                 type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer,                type: "costmap_2d::InflationLayer"}
